env:
  browser: true
  es2021: true
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./tsconfig.json"
    - "./packages/*/tsconfig.json"
  sourceType: "module"
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
root: true
plugins:
  - "@typescript-eslint"
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
